{
 "title": "Crawler",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current traffic (msgs/sec).",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(crawler_messages_received_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current crawl rate (pages/sec)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(crawl_pages_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Messages Received Successfully (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(crawler_messages_received_total{status=\"valid\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(crawler_messages_received_total[$__rate_interval])), 1e-12)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Messages Published Successfully (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(crawler_published_messages_total{status=\"success\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(crawler_published_messages_total[$__rate_interval])), 1e-12)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Errors (errors/sec)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(crawl_pages_failures_total[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic (workload)",
   "type": "timeseries",
   "description": "Incoming workload in messages/sec across all instances. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(crawler_messages_received_total[$__rate_interval]))",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "Pages Crawled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(crawl_pages_total[$__rate_interval]))",
     "legendFormat": "Pages Crawled"
    }
   ]
  },
  {
   "title": "Successfully Received Messages (%)",
   "type": "timeseries",
   "description": "% of received messages handled successfully. ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(crawler_messages_received_total{status=\"valid\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(crawler_messages_received_total[$__rate_interval])), 1e-12)",
     "legendFormat": "Message Received Successfully"
    }
   ]
  },
  {
   "title": "Successfully Published Messages (%)",
   "type": "timeseries",
   "description": "% of publishes to RabbitMQ that succeeded.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(crawler_published_messages_total{status=\"success\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(crawler_published_messages_total[$__rate_interval])), 1e-12)",
     "legendFormat": "Message Published Successfully"
    }
   ]
  },
  {
   "title": "Failures & Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(crawl_pages_failures_total[$__rate_interval])) or vector(0)",
     "legendFormat": "Failures & Errors"
    }
   ]
  },
  {
   "title": "Process - Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (stage, le) (\n    rate(page_crawl_latency_seconds_bucket{stage=\"total_latency\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "Total Latency"
    }
   ]
  },
  {
   "title": "Latency p95 - Per Stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (stage, le) (rate(page_crawl_latency_seconds_bucket{stage=~\".+\", stage!=\"total_latency\"}[$__rate_interval]))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}