{
 "title": "Rescheduler",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Number Of Pages Rescheduled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rescheduler_pages_rescheduled_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Messages Published Successfully (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rescheduler_crawl_tasks_published_total{status=\"success\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(rescheduler_crawl_tasks_published_total[$__rate_interval])), 1e-12)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Errors (errors/sec)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rescheduler_errors_total[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pages Rescheduled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rescheduler_pages_rescheduled_total",
     "legendFormat": "Pages"
    }
   ]
  },
  {
   "title": "Successfully Published Messages (%)",
   "type": "timeseries",
   "description": "% of publishes to RabbitMQ that succeeded",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(rescheduler_crawl_tasks_published_total{status=\"success\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(rescheduler_crawl_tasks_published_total[$__rate_interval])), 1e-12)",
     "legendFormat": "Message Published Successfully"
    }
   ]
  },
  {
   "title": "Failures & Errors",
   "type": "timeseries",
   "description": "Throughput of links extracted (links/sec). Drops may indicate parsing problems or reduced coverage.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(rescheduler_errors_total[$__rate_interval])) or vector(0)",
     "legendFormat": "Failures & Errors"
    }
   ]
  },
  {
   "title": "Process - Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(rescheduler_reschedule_latency_seconds_bucket[$__rate_interval]))\n)\n",
     "legendFormat": "Total Latency"
    }
   ]
  }
 ]
}