{
 "title": "Scheduler",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Links currently processing (links/sec).",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_links_received_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links Scheduled / Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_links_scheduled_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links deduplicated / Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_links_deduplicated_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links filtered / Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_links_filtered_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Receives / Sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_messages_received_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Messages Received Successfully (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_messages_received_total{status=\"valid\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(scheduler_messages_received_total[$__rate_interval])), 1e-12)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Messages Published Successfully (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scheduler_published_messages_total{status=\"success\"})\n/\nclamp_min(sum(scheduler_published_messages_total), 1e-12)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Errors (errors/sec)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(crawl_pages_failures_total[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links Processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_links_received_total[$__rate_interval]))",
     "legendFormat": "Links Processing"
    }
   ]
  },
  {
   "title": "Links Scheduled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_links_scheduled_total[$__rate_interval]))",
     "legendFormat": "Links Scheduled"
    }
   ]
  },
  {
   "title": "Links Filtered",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (filter_type) (rate(scheduler_links_filtered_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Links deduplicated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_links_deduplicated_total[$__rate_interval]))",
     "legendFormat": "Links Deduplicated"
    }
   ]
  },
  {
   "title": "Traffic (workload)",
   "type": "timeseries",
   "description": "Incoming workload in messages/sec across all instances. ",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_messages_received_total[$__rate_interval]))",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "Successfully Received Messages (%)",
   "type": "timeseries",
   "description": "% of received messages handled successfully. ",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_messages_received_total{status=\"valid\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(scheduler_messages_received_total[$__rate_interval])), 1e-12)",
     "legendFormat": "Message Received Successfully"
    }
   ]
  },
  {
   "title": "Successfully Published Messages (%)",
   "type": "timeseries",
   "description": "% of publishes to RabbitMQ that succeeded.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(scheduler_published_messages_total{status=\"success\"})\n/\nclamp_min(sum(scheduler_published_messages_total), 1e-12)",
     "legendFormat": "Message Published Successfully"
    }
   ]
  },
  {
   "title": "Failures & Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(crawl_pages_failures_total[$__rate_interval])) or vector(0)",
     "legendFormat": "Failures & Errors"
    }
   ]
  },
  {
   "title": "Process - Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (stage, le) (\n    rate(scheduler_processing_duration_seconds_bucket{stage=\"total_latency\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "Total Latency"
    }
   ]
  },
  {
   "title": "Latency p95 - Per Stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (stage, le) (rate(scheduler_processing_duration_seconds_bucket{stage=~\".+\", stage!=\"total_latency\"}[$__rate_interval]))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}