services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    env_file: .env
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_init:
    container_name: db_init
    build:
      context: .
      dockerfile: db_init/Dockerfile
    depends_on:
      - postgres
    env_file: .env # Only used in local dev
    command: [ "python", "-m", "db_init.db_init" ]

  crawler_ashburn:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    depends_on:
      - postgres
      - db_init
      - rabbitmq
      - redis
    env_file: .env # Only used in local dev
    environment:
      - HTTP_PROXY=${ASHBURN_PROXY}
      - HTTPS_PROXY=${ASHBURN_PROXY}
      - NO_PROXY=localhost,127.0.0.1,rabbitmq,redis,postgres,192.168.0.0/16
    command: [ "python", "-m", "crawler.crawler" ]
    volumes:
      - compressed_html_data:${DL_HTML_PATH}
  # ===========================================
  # Testing services for proxies/vpn services
  # ===========================================

  # testapp:
  #   image: curlimages/curl
  #   container_name: testapp
  # environment:
  #   - HTTP_PROXY=${DALLAS2_PROXY}
  #   - HTTPS_PROXY=${DALLAS2_PROXY}
  #   - NO_PROXY=localhost,127.0.0.1,rabbitmq,redis,postgres,192.168.0.0/16
  # command: [ "curl", "-sS", "https://am.i.mullvad.net/json" ]
  # command: [ "curl", "-sS", "http://192.168.86.15:15672/" ]


volumes:
  pg_data:
  compressed_html_data:


