services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    env_file: .env
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_init:
    container_name: db_init
    build:
      context: .
      dockerfile: db_init/Dockerfile
    depends_on:
      - postgres
    env_file: .env # Only used in local dev
    command: [ "python", "-m", "db_init.db_init" ]

  crawler:
    # container_name: crawler
    build:
      context: .
      dockerfile: crawler/Dockerfile
    depends_on:
      - postgres
      - db_init
      - rabbitmq
      - redis
    env_file: .env # Only used in local dev
    command: [ "python", "-m", "crawler.crawler" ]
    volumes:
      - compressed_html_data:${DL_HTML_PATH}
  # prometheus:
  #   image: prom/prometheus
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana

volumes:
  pg_data:
  compressed_html_data:
