global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.86.15:9100"] # dev for now

  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.86.15:8080"] # dev for now

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']