global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prod-node-exporter"
    static_configs:
      - targets: ["192.168.86.16:9100"]
        labels:
          env: prod

  - job_name: "prod-cadvisor"
    static_configs:
      - targets: ["192.168.86.16:8080"]
        labels:
          env: prod
  
  - job_name: "crawlers"
    dns_sd_configs:
      - names: ["crawler"]   # the shared network alias
        type: A
        port: 8000

  - job_name: 'parsers'
    dns_sd_configs:
      - names: ['parser']
        type: A
        port: 8000


  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          env: prod