services:
  crawler_noproxy:
    extends:
      file: ./docker-compose.yml
      service: crawler_noproxy
    environment:
      - APP_ENV=dev

  parser:
    extends:
      file: ./docker-compose.yml
      service: parser
    environment:
      - APP_ENV=dev

  scheduler:
    extends:
      file: ./docker-compose.yml
      service: scheduler
    environment:
      - APP_ENV=dev

  dispatcher:
    extends:
      file: ./docker-compose.yml
      service: dispatcher
    environment:
      - APP_ENV=dev

  rescheduler:
    extends:
      file: ./docker-compose.yml
      service: rescheduler
    environment:
      - APP_ENV=dev
