services:
  crawler_noproxy:
    extends:
      file: ./docker-compose.yml
      service: crawler_noproxy
    environment:
      - APP_ENV=prod

  parser:
    extends:
      file: ./docker-compose.yml
      service: parser
    environment:
      - APP_ENV=prod

  scheduler:
    extends:
      file: ./docker-compose.yml
      service: scheduler
    environment:
      - APP_ENV=prod

  dispatcher:
    extends:
      file: ./docker-compose.yml
      service: dispatcher
    environment:
      - APP_ENV=prod
