redis:
  host: redis
  # host: 192.168.86.15
  port: 6379
  db_seen: 0
  decode_responses: true

postgres:
  host: postgres
  # host: 192.168.86.15
  port: 5432

rabbitmq:
  host: rabbitmq
  # host: 192.168.86.15
  port: 5672

# http headers
headers:
  accept: text/html
  accept-language: en-US
  user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36

