storage:
  compressed_html_dir: /app/data/compressed_html_data

logging:
  log_to_file: true
  log_level: INFO

redis:
  host: redis
  port: 6379
  db_seen: 0
  ttl: 3600
  decode_responses: true

postgres:
  url: ${DATABASE_URL}

rabbitmq:
  user: ${RABBITMQ_USER}
  password: ${RABBITMQ_PASSWORD}
  host: rabbitmq
  port: 5672

wikipedia:
  max_depth: 4
  base_url: https://en.wikipedia.org
  seed_url: https://en.wikipedia.org/wiki/Computer_science
  robots_txt: https://en.wikipedia.org/robots.txt
