default:
  redis:
    host: redis
    port: 6379
    db_seen: 0
    decode_responses: true

  postgres:
    host: postgres
    port: 5432
    db: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${DATABASE_URL}

  rabbitmq:
    user: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    host: rabbitmq
    port: 5672

  wikipedia:
    base_url: https://en.wikipedia.org
    seed_url: https://en.wikipedia.org/wiki/Computer_science
    robots_txt: https://en.wikipedia.org/robots.txt
