excluded_prefixes:
  - "/wiki/Special:"
  - "/wiki/Help:"
  - "/wiki/Portal:"
  - "/wiki/File:"
  - "/wiki/Template:"
  - "/wiki/Template_talk:"
  - "/wiki/Wikipedia:"
  - "/wiki/Talk:"
  - "/wiki/Category:"
  - "/wiki/Book:"
  - "/wiki/User:"
  - "/wiki/Module:"
  - "/wiki/Project:"
  - "/wiki/Main_Page"