
wikipedia:
  base_url: https://en.wikipedia.org

http_headers:
  accept: text/html
  accept-language: en-US
  user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36


filters:
  robots_txt: https://en.wikipedia.org/robots.txt

  allowed_domains:
    - en.wikipedia.org
  
  # TODO: Imple the use of this in the code
  excluded_prefixes:
    - "/wiki/Special:"
    - "/wiki/Help:"
    - "/wiki/Portal:"
    - "/wiki/File:"
    - "/wiki/Template:"
    - "/wiki/Template_talk:"
    - "/wiki/Wikipedia:"
    - "/wiki/Talk:"
    - "/wiki/Category:"
    - "/wiki/Book:"
    - "/wiki/User:"
    - "/wiki/Module:"
    - "/wiki/Project:"
    - "/wiki/Main_Page"