logging:
  log_to_file: true
  log_level: INFO
  logger_name: Dispatcher

# adjust to the desire number of pages you want to crawl/sec
dispatch_count: 6

# seconds between each dispatch
dispatch_tick: 1 

db_reader_timeout_seconds: 10

seed_urls:
  - https://en.wikipedia.org/wiki/Computer_science