logging:
  log_to_file: true
  log_level: DEBUG
  logger_name: Dispatcher

dispatch_count: 1

seed_urls:
  - https://en.wikipedia.org/wiki/Computer_science

# seconds between each dispatch
dispatch_tick: 1