logging:
  log_to_file: true
  log_level: INFO
  logger_name: Dispatcher

dispatch_count: 60

# seconds between each dispatch
dispatch_tick: 1 

db_reader_timeout_seconds: 10

seed_urls:
  - https://en.wikipedia.org/wiki/Computer_science