logging:
  log_to_file: true
  log_level: DEBUG
  logger_name: Dispatcher

dispatch_count: 1

# TODO: remove heartbeat configs if its no longer needed
# heartbeat_key_pattern: "crawler:*:heartbeat"
# scan_count: 1000

seed_urls:
  - https://en.wikipedia.org/wiki/Computer_science

# seconds between each dispatch
dispatch_tick: 1