logging:
  log_to_file: true
  log_level: INFO
  logger_name: Dispatcher

dispatch_count: 24
# TODO: remove heartbeat configs if its no longer needed
# heartbeat_key_pattern: "crawler:*:heartbeat"
# scan_count: 1000

seed_urls:
  - https://en.wikipedia.org/wiki/Computer_science

dispatch_tick: 1 #seconds between each dispatch