logging:
  log_to_file: true
  log_level: INFO
  logger_name: Dispatcher

heartbeat_key_pattern: "crawler:*:heartbeat"
scan_count: 100

seed_urls:
  - https://en.wikipedia.org/wiki/Computer_science

dispatch_tick: 1 #seconds between each dispatch