name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      DL_HTML_PATH: ${{ secrets.DL_HTML_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff linter
        run: |
          pip install ruff
          ruff check .

      - name: Generate .env file
        run: |
          echo "RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}" >> .env
          echo "RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DL_HTML_PATH=${{ secrets.DL_HTML_PATH }}" >> .env

      - name: Check docker-compose syntax
        run: docker compose config
  
  image-build-test:
    runs-on: ubuntu-latest
    env:
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      DL_HTML_PATH: ${{ secrets.DL_HTML_PATH }}
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env file
        run: |
          echo "RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}" >> .env
          echo "RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DL_HTML_PATH=${{ secrets.DL_HTML_PATH }}" >> .env

      - name: Build services
        run: |
          docker compose build

  unit-test:
    runs-on: ubuntu-latest
    env:
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      DL_HTML_PATH: ${{ secrets.DL_HTML_PATH }}
    needs: image-build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pytest
          pip install testcontainers
          pip install -r requirements-common.txt

          for d in components/*; do
            if [ -f "$d/requirements.txt" ]; then
              echo "Installing from $d/requirements.txt"
              cd "$d"
              pip install -r requirements.txt
              cd - > /dev/null
            fi
          done

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run test suite
        run: pytest tests/
        
