name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      DL_HTML_PATH: ${{ secrets.DL_HTML_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff linter
        run: |
          pip install ruff
          ruff check .

      - name: Check docker-compose syntax
        run: docker compose config
  
  image-build-test:
    runs-on: ubuntu-latest
    env:
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      DL_HTML_PATH: ${{ secrets.DL_HTML_PATH }}
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build services
        run: |
          docker compose build

  unit-test:
    runs-on: ubuntu-latest
    env:
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
      DL_HTML_PATH: ${{ secrets.DL_HTML_PATH }}
    needs: image-build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install root-level dependencies
        run: pip install -r requirements-common.txt

      - name: Install all component dependencies
        run: |
          for d in components/*; do
            if [ -f "$d/requirements.txt" ]; then
              pip install -r "$d/requirements.txt"
            fi
          done

      - name: Run test suite
        run: pytest test/
        
